import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web4 from '../public/web4.png'
import web6 from '../public/web6.png'
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Gyovani Santos - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-200 px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons'>ROOT</h1>
          <ul className='flex items-center'>
            <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
            </li>
            <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Gyovani Santos</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Desenvolvedor WEB</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Sou desenvolvedor WEB, técnico em Redes de Computadores e estou cursando Sistemas de Informações. Conheça abaixo alguns de meus projetos:
              </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <AiFillTwitterCircle/>
          <AiFillLinkedin/>
          <AiFillYoutube/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={deved} layout="fill" objectFit="cover"/>
        </div>
        </section>
        
   <section>
    <div>
      <br />
     <h3 className='text-center text-3xl py-1 max-w-xl  mx-auto'>Serviços que ofereço</h3>
            <p className='text-center text-xl py-2 leading-8 text-gray-800 max-w-xl mx-auto'>Atualmente, possuo disponibilidade para trabalhar como <span className='text-teal-500'>freelancer</span> e se necessário de forma <span className='text-teal-500'>remota</span>, possuo conhecimento em gerenciamento de redes, desenvolvimento WEB e desenvolvimento de chatbots.</p>
            <p className=' text-center text-xl py-2 leading-8 text-gray-800 max-w-xl mx-auto'>Além disso, já desenvolvi pesquisas na área de <span className='text-teal-500'>Desenvolvimento Sustentável em TI</span> e atualmente na área de <span className='text-teal-500'>Big Data</span>.
              </p>
            </div>
            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={design} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Título de algum projeto</h3>
                <p className='py-2'>
                  bla bla falar de algum projeto meu, bla bla, bla bla bla.
                </p>
                <h4 className='py-4 text-teal-600'>Tecnologias que Uso</h4>
                <p className='text-gray-800 py-1'>React</p>
                <p className='text-gray-800 py-1'>NextJS</p>
                <p className='text-gray-800 py-1'>Tailwind</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={consulting} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Título de algum projeto</h3>
                <p className='py-2'>
                  bla bla falar de algum projeto meu, bla bla, bla bla bla.
                </p>
                <h4 className='py-4 text-teal-600'>Tecnologias que Uso</h4>
                <p className='text-gray-800 py-1'>React</p>
                <p className='text-gray-800 py-1'>NextJS</p>
                <p className='text-gray-800 py-1'>Tailwind</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={code} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Título de algum projeto</h3>
                <p className='py-2'>
                  bla bla falar de algum projeto meu, bla bla, bla bla bla.
                </p>
                <h4 className='py-4 text-teal-600'>Tecnologias que Uso</h4>
                <p className='text-gray-800 py-1'>React</p>
                <p className='text-gray-800 py-1'>NextJS</p>
                <p className='text-gray-800 py-1'>Tailwind</p>
              </div>
            </div>
         </section>
         <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Atualmente, possuo disponibilidade para trabalhar como <span className='text-teal-500'>freelancer</span> e se necessário de forma <span className='text-teal-500'>remota</span>, possuo conhecimento em gerenciamento de redes, desenvolvimento WEB e desenvolvimento de chatbots.</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Além disso, já desenvolvi pesquisas na área de <span className='text-teal-500'>Desenvolvimento Sustentável em TI</span> e atualmente na área de <span className='text-teal-500'>Big Data</span>.
              </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

          <div className='basis-1/3 flex-1'> 
          <Image src={web1} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>

          <div className='basis-1/3 flex-1'><Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>

          

          <div className='basis-1/3 flex-1'><Image src={web4} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>


          <div className='basis-1/3 flex-1'><Image src={web6} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>

          </div>
         </section>
      </main>
   </div>
  )
}
